module.exports = {
  parser: 'espree',
  ecmaFeatures: {},
  rules: {
    // Possible Errors
    'comma-dangle': [2, 'never'],
    'no-cond-assign': 2,
    'no-console': 2,
    'no-constant-condition': 2,
    'no-control-regex': 2,
    'no-debugger': 2,
    'no-dupe-args': 2,
    'no-dupe-keys': 2,
    'no-duplicate-case': 2,
    'no-empty-character-class': 2,
    'no-empty': 2,
    'no-ex-assign': 2,
    'no-extra-boolean-cast': 2,
    'no-extra-parens': 0,
    'no-extra-semi': 2,
    'no-func-assign': 2,
    'no-inner-declarations': [2, 'functions'],
    'no-invalid-regexp': 2,
    'no-irregular-whitespace': 2,
    'no-negated-in-lhs': 2,
    'no-obj-calls': 2,
    'no-regex-spaces': 2,
    'no-sparse-arrays': 2,
    'no-unreachable': 2,
    'use-isnan': 2,
    'valid-jsdoc': [2, {'prefer': {'return': 'returns'}}],
    'valid-typeof': 2,
    'no-unexpected-multiline': 2,

    // Best Practices
    'accessor-pairs': [2, {'setWithoutGet': true}],
    'block-scoped-var': 0,
    'complexity': [2, 11],
    'consistent-return': 2,
    'curly': [2, 'all'],
    'default-case': 2,
    'dot-notation': [2, {'allowKeywords': true, 'allowPattern': '^[a-z]+(_[a-z]+)+$'}],
    'dot-location': [2, 'property'],
    'eqeqeq': [2, 'smart'],
    'guard-for-in': 2,
    'no-alert': 0,
    'no-caller': 2,
    'no-case-declarations': 2,
    'no-div-regex': 2,
    'no-else-return': 2,
    'no-empty-label': 2,
    'no-empty-pattern': 2,
    'no-eq-null': 2,
    'no-eval': 2,
    'no-extend-native': 2,
    'no-extra-bind': 2,
    'no-fallthrough': 2,
    'no-floating-decimal': 2,
    'no-implicit-coercion': 2,
    'no-implied-eval': 2,
    'no-invalid-this': 0,
    'no-iterator': 2,
    'no-labels': 2,
    'no-lone-blocks': 2,
    'no-loop-func': 2,
    'no-magic-numbers': 2,
    'no-multi-spaces': [2, {'exceptions': {'ImportDeclaration': true, 'VariableDeclarator': true, 'AssignmentExpression': true}}],
    'no-multi-str': 2,
    'no-native-reassign': 2,
    'no-new-func': 2,
    'no-new-wrappers': 2,
    'no-new': 2,
    'no-octal-escape': 2,
    'no-octal': 2,
    'no-param-reassign': 2,
    'no-process-env': 1,
    'no-proto': 2,
    'no-redeclare': 2,
    'no-return-assign': 2,
    'no-script-url': 2,
    'no-self-compare': 2,
    'no-sequences': 2,
    'no-throw-literal': 2,
    'no-unused-expressions': 2,
    'no-useless-call': 2,
    'no-useless-concat': 2,
    'no-void': 0,
    'no-warning-comments': [0, {'terms': ['todo', 'fixme', 'xxx'], 'location': 'start'}],
    'no-with': 2,
    'radix': 2,
    'vars-on-top': 0,
    'wrap-iife': 2,
    'yoda': [2, 'never', {'exceptRange': true, 'onlyEquality': true}],

    // Strict Mode
    'strict': [2, 'function'],

    // Variables
    'init-declarations': 0,
    'no-catch-shadow': 2,
    'no-delete-var': 2,
    'no-label-var': 2,
    'no-shadow-restricted-names': 2,
    'no-shadow': 2,
    'no-undef-init': 2,
    'no-undef': 2,
    'no-undefined': 2,
    'no-unused-vars': [2, {'vars': 'all', 'args': 'after-used'}],
    'no-use-before-define': 2,

    // Node.js and CommonJS
    'callback-return': [2, ['cb', 'callback', 'next']],
    'global-require': 2,
    'handle-callback-err': [2, '^(err|error)$'],
    'no-mixed-requires': 2,
    'no-new-require': 2,
    'no-path-concat': 2,
    'no-process-exit': 2,
    'no-restricted-modules': 0,
    'no-sync': 0,

    // Stylistic Issues
    'array-bracket-spacing': [2, 'never'],
    'block-spacing': [2, 'always'],
    'brace-style': [2, '1tbs'],
    'camelcase': [2, {'properties': 'never'}],
    'comma-spacing': [2, {'before': false, 'after': true}],
    'comma-style': [2, 'last'],
    'computed-property-spacing': [2, 'never'],
    'consistent-this': [2, 'self'],
    'eol-last': 2,
    'func-names': 0,
    'func-style': [2, 'declaration'],
    'id-length': [2, {'min': 2, 'properties': 'never', 'exceptions': ['$', '_']}],
    'id-match': 0,
    'indent': [2, 2, {'SwitchCase': 1}],
    'jsx-quotes': [2, 'prefer-double'],
    'key-spacing': [2, {'beforeColon': false, 'afterColon': true, 'mode': 'minimum'}],
    'lines-around-comment': [2, {'beforeBlockComment': true}],
    'linebreak-style': [2, 'unix'],
    'max-nested-callbacks': [2, 4],
    'new-cap': [2, {'newIsCap': true, 'capIsNew': true}],
    'new-parens': 2,
    'newline-after-var': [0, 'always'],
    'no-array-constructor': 2,
    'no-continue': 2,
    'no-inline-comments': 0,
    'no-lonely-if': 2,
    'no-mixed-spaces-and-tabs': [2, false],
    'no-multiple-empty-lines': [2, {'max': 2, 'maxEOF': 1}],
    'no-nested-ternary': 2,
    'no-negated-condition': 0,
    'no-new-object': 2,
    'no-restricted-syntax': [2, 'WithStatement'],
    'no-spaced-func': 2,
    'no-ternary': 0,
    'no-trailing-spaces': 2,
    'no-underscore-dangle': 2,
    'no-unneeded-ternary': 2,
    'object-curly-spacing': [2, 'never'],
    'one-var': [2, {'uninitialized': 'always', 'initialized': 'never'}],
    'operator-assignment': [2, 'always'],
    'operator-linebreak': [2, 'after'],
    'padded-blocks': [2, 'never'],
    'quote-props': [2, 'consistent-as-needed', {'keywords': true}],
    'quotes': [2, 'single', 'avoid-escape'],
    'require-jsdoc': 2,
    'semi-spacing': [2, {'before': false, 'after': true}],
    'semi': [2, 'always'],
    'sort-vars': 0,
    'space-after-keywords': [2, 'always'],
    'space-before-keywords': [2, 'always'],
    'space-before-blocks': [2, 'always'],
    'space-before-function-paren': [2, {'anonymous': 'always', 'named': 'never'}],
    'space-in-parens': [2, 'never'],
    'space-infix-ops': 2,
    'space-return-throw-case': 2,
    'space-unary-ops': [2, {'words': true, 'nonwords': false}],
    'spaced-comment': [2, 'always', {'exceptions': ['-']}],
    'wrap-regex': 2,

    // ECMAScript 6
    'arrow-body-style': 0,
    'arrow-parens': 0,
    'arrow-spacing': 0,
    'constructor-super': 0,
    'generator-star-spacing': 0,
    'no-arrow-condition': 0,
    'no-class-assign': 0,
    'no-const-assign': 0,
    'no-dupe-class-members': 0,
    'no-this-before-super': 0,
    'no-var': 0,
    'object-shorthand': 0,
    'prefer-arrow-callback': 0,
    'prefer-const': 0,
    'prefer-spread': 0,
    'prefer-reflect': 0,
    'prefer-template': 0,
    'require-yield': 0,

    // Legacy
    'max-depth': [2, 4],
    'max-len': [2, 100, 4, {'ignoreComments': true, 'ignoreUrls': true}],
    'max-params': [2, 4],
    'max-statements': [2, 15],
    'no-bitwise': 2,
    'no-plusplus': [2, {'allowForLoopAfterthoughts': true}]
  }
};
