name: Test
on:
  merge_group: {}
  pull_request: {}
  push:
    branches: [main]
  workflow_dispatch: {}
permissions: {}
jobs:
  required:
    name: "Required Checks: Test"
    if: ${{ always() }}
    needs:
      - verify-author
      - changed-files
      - actionlint
      - ghalint
      - zizmor
      - check
      - editorconfig
      - eslint
      - prettier
      - test
      - yamllint
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Fail if any required jobs failed or cancelled
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: exit 1
  verify-author:
    name: Verify author
    environment: ${{ github.event_name == 'pull_request' &&
      endsWith(github.event.pull_request.user.login, '[bot]') &&
      contains(github.event.pull_request.labels.*.name, 'dependencies') &&
      contains(github.event.pull_request.labels.*.name, 'github_actions') && 'ci' || null }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Author has been verified
        run: exit 0
  changed-files:
    name: Get changed files
    if: ${{ github.event_name == 'pull_request' }}
    needs: verify-author
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    outputs:
      # reference: https://github.com/tj-actions/changed-files#outputs-
      actions: ${{ steps.changed-files.outputs.actions_any_modified == 'true' }}
      config: ${{ steps.changed-files.outputs.config_any_modified == 'true' }}
      eslint: ${{ steps.changed-files.outputs.eslint_any_modified == 'true' }}
      prettier: ${{ steps.changed-files.outputs.prettier_any_modified == 'true' }}
      yamllint: ${{ steps.changed-files.outputs.yamllint_any_modified == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          fetch-depth: 50 # Assume PRs are less than 50 commits
          persist-credentials: true
      - name: Get relevant files changed per group
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46.0.5
        with:
          files_yaml: |
            common: &common
              - .github/workflows/test.yml
            dependencies: &dependencies
              - package-lock.json
              - package.json
            config: &config
              - *common
              - *dependencies
              - base.js
              - browser.js
              - index.js
              - node.js
            actions:
              - "**/action.{yaml,yml}"
              - ".github/workflows/*.{yaml,yml}"
            eslint:
              - *config
              - "**/*.{cjs,js,mjs}"
              - eslint.config.*
            prettier:
              - *config
              - "**/*.{cjs,js,json,md,mjs,yaml,yml}"
              - prettier.config.*
            yamllint:
              - *common
              - "**/*.{yaml,yml}"
  actionlint:
    name: actionlint
    if: ${{ always() && !failure() && !cancelled() &&
      (needs.changed-files.result == 'skipped' || needs.changed-files.outputs.actions == 'true') }}
    needs: changed-files
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false
      - name: Run actionlint
        uses: ponko2/actions/actionlint@main
  ghalint:
    name: ghalint
    if: ${{ always() && !failure() && !cancelled() &&
      (needs.changed-files.result == 'skipped' || needs.changed-files.outputs.actions == 'true') }}
    needs: changed-files
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false
      - name: Run ghalint
        uses: ponko2/actions/ghalint@main
  zizmor:
    name: zizmor
    if: ${{ always() && !failure() && !cancelled() &&
      (needs.changed-files.result == 'skipped' || needs.changed-files.outputs.actions == 'true') }}
    needs: changed-files
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false
      - name: Run zizmor
        uses: ponko2/actions/zizmor@main
  check:
    name: Check
    if: ${{ always() && !failure() && !cancelled() &&
      (needs.changed-files.result == 'skipped' || needs.changed-files.outputs.config == 'true') }}
    needs: changed-files
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false
      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: lts/*
          cache: npm
      - run: npm ci
      - run: npm run check
  editorconfig:
    name: EditorConfig
    needs: verify-author
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false
      - uses: editorconfig-checker/action-editorconfig-checker@0ab3427a3f09b17c21d489172245be511e0a16ea # v2.0.0
      - run: editorconfig-checker
  eslint:
    name: ESLint
    if: ${{ always() && !failure() && !cancelled() &&
      (needs.changed-files.result == 'skipped' || needs.changed-files.outputs.eslint == 'true') }}
    needs: changed-files
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false
      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: lts/*
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Add problem matchers
        run: echo "::add-matcher::.github/eslint-matcher.json"
      - name: Run ESLint
        run: npm run lint:eslint
  prettier:
    name: Prettier
    if: ${{ always() && !failure() && !cancelled() &&
      (needs.changed-files.result == 'skipped' || needs.changed-files.outputs.prettier == 'true') }}
    needs: changed-files
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false
      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: lts/*
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run Prettier
        run: npm run lint:prettier
  test:
    name: Test
    if: ${{ always() && !failure() && !cancelled() &&
      (needs.changed-files.result == 'skipped' || needs.changed-files.outputs.config == 'true') }}
    needs: changed-files
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    strategy:
      matrix:
        node-version:
          - lts/*
          - lts/-1
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm test
  yamllint:
    name: yamllint
    if: ${{ always() && !failure() && !cancelled() &&
      (needs.changed-files.result == 'skipped' || needs.changed-files.outputs.yamllint == 'true') }}
    needs: changed-files
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false
      - name: Run yamllint
        run: yamllint --format=github --strict .
