name: Test
on:
  push:
    branches: [main]
  pull_request: {}
  workflow_dispatch: {}
permissions: {}
jobs:
  required:
    name: "Required Checks: Test"
    if: ${{ always() }}
    needs:
      - actionlint
      - changed-files
      - check
      - editorconfig
      - eslint
      - ghalint
      - prettier
      - test
      - triggering-actor
      - yamllint
      - zizmor
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Determine status
        id: status
        run: |
          results=$(tr -d '\n' <<< '${{ toJSON(needs.*.result) }}')
          if ! grep -q -v -E '(failure|cancelled)' <<< "$results"; then
            result="failed"
          else
            result="success"
          fi
          {
            echo "result=${result}"
            echo "results=${results}"
          } | tee -a "$GITHUB_OUTPUT"
      - name: Check for failed status
        if: ${{ always() && steps.status.outputs.result != 'success' }}
        run: |
          echo "One or more required build workflows failed: ${{ steps.status.outputs.results }}"
          exit 1
  triggering-actor:
    name: Validate triggering actor
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Fail if the triggering actor is a bot
        if: ${{ github.event_name == 'pull_request' &&
          endsWith(github.triggering_actor, '[bot]') &&
          contains(github.event.pull_request.labels.*.name, 'dependencies') &&
          contains(github.event.pull_request.labels.*.name, 'github_actions') }}
        run: exit 1
  changed-files:
    name: Get changed files
    needs: triggering-actor
    runs-on: ubuntu-latest
    timeout-minutes: 60
    outputs:
      # reference: https://github.com/tj-actions/changed-files#outputs-
      config: ${{ steps.changed-files.outputs.config_any_modified == 'true' }}
      eslint: ${{ steps.changed-files.outputs.eslint_any_modified == 'true' }}
      prettier: ${{ steps.changed-files.outputs.prettier_any_modified == 'true' }}
      workflows: ${{ steps.changed-files.outputs.workflows_any_modified == 'true' }}
      yamllint: ${{ steps.changed-files.outputs.yamllint_any_modified == 'true' }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 50 # Assume PRs are less than 50 commits
          persist-credentials: false
      - name: Get relevant files changed per group
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46.0.5
        with:
          files_yaml: |
            common: &common
              - .github/workflows/test.yml
            dependencies: &dependencies
              - package-lock.json
              - package.json
            config: &config
              - *common
              - *dependencies
              - base.js
              - browser.js
              - index.js
              - node.js
            eslint:
              - *config
              - "**.{cjs,js,mjs}"
              - eslint.config.*
            prettier:
              - *config
              - "**.{cjs,js,json,md,mjs,yaml,yml}"
              - prettier.config.*
            workflows:
              - ".github/workflows/*.{yaml,yml}"
            yamllint:
              - *common
              - "**.{yaml,yml}"
  actionlint:
    name: actionlint
    if: ${{ needs.changed-files.outputs.workflows == 'true' }}
    needs:
      - changed-files
      - triggering-actor
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: reviewdog/action-actionlint@a5524e1c19e62881d79c1f1b9b6f09f16356e281 # v1.65.2
        with:
          fail_level: warning
          filter_mode: nofilter
          reporter: github-pr-annotations
  check:
    name: Check
    if: ${{ needs.changed-files.outputs.config == 'true' }}
    needs:
      - changed-files
      - triggering-actor
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: lts/*
          cache: npm
      - run: npm ci
      - run: npm run check
  editorconfig:
    name: EditorConfig
    needs: triggering-actor
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: editorconfig-checker/action-editorconfig-checker@0ab3427a3f09b17c21d489172245be511e0a16ea # v2.0.0
      - run: editorconfig-checker
  eslint:
    name: ESLint
    if: ${{ needs.changed-files.outputs.eslint == 'true' }}
    needs:
      - changed-files
      - triggering-actor
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: lts/*
          cache: npm
      - name: Install dependencies
        run: npm ci
      - uses: reviewdog/action-eslint@2fee6dd72a5419ff4113f694e2068d2a03bb35dd # v1.33.2
        with:
          fail_level: error
          filter_mode: nofilter
          reporter: github-pr-annotations
          tool_name: ESLint
  ghalint:
    name: ghalint
    if: ${{ needs.changed-files.outputs.workflows == 'true' }}
    needs:
      - changed-files
      - triggering-actor
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Set up ghalint
        env:
          GHALINT_VERSION: v1.3.0
          GH_TOKEN: ${{ github.token }}
        run: |
          TMPDIR=$(mktemp -d)
          gh release download "$GHALINT_VERSION" -R suzuki-shunsuke/ghalint -p "ghalint_*_linux_amd64.tar.gz" -O "$TMPDIR/ghalint.tar.gz"
          gh attestation verify "$TMPDIR/ghalint.tar.gz" -R suzuki-shunsuke/ghalint --signer-workflow suzuki-shunsuke/go-release-workflow/.github/workflows/release.yaml
          tar -C /usr/local/bin -xzf "$TMPDIR/ghalint.tar.gz"
      - name: Run ghalint
        run: ghalint run
  prettier:
    name: Prettier
    if: ${{ needs.changed-files.outputs.prettier == 'true' }}
    needs:
      - changed-files
      - triggering-actor
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: lts/*
          cache: npm
      - name: Install dependencies
        run: npm ci
      - run: npx prettier --write .
      - uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893 # v1.3.2
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TMPFILE=$(mktemp)
          git diff >"${TMPFILE}"
          { git stash -u && git stash drop; } || true
          reviewdog -f=diff -fail-level=error -filter-mode=nofilter -name=Prettier -reporter=github-pr-annotations <"${TMPFILE}"
  test:
    name: Test
    if: ${{ needs.changed-files.outputs.config == 'true' }}
    needs:
      - changed-files
      - triggering-actor
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    strategy:
      matrix:
        node-version:
          - lts/*
          - lts/-1
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm test
  yamllint:
    name: yamllint
    if: ${{ needs.changed-files.outputs.yamllint == 'true' }}
    needs:
      - changed-files
      - triggering-actor
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: reviewdog/action-yamllint@f01d8a48fd8d89f89895499fca2cff09f9e9e8c0 # v1.21.0
        with:
          fail_level: error
          filter_mode: nofilter
          reporter: github-pr-annotations
  zizmor:
    name: zizmor
    if: ${{ needs.changed-files.outputs.workflows == 'true' }}
    needs:
      - changed-files
      - triggering-actor
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@6b9c6063abd6010835644d4c2e1bef4cf5cd0fca # v6.0.1
        with:
          enable-cache: false
      - name: Run zizmor
        env:
          GH_TOKEN: ${{ github.token }}
        run: uvx zizmor@1.6.0 -p --format=github --min-severity=low .github/workflows
